#!/usr/bin/env python3
"""
bin2headers_group0.py

Lab 5 – DNN on MNIST (Group 0)
Converts binary weight/bias files and test images from group_0/ to C header files.

Input:
  - group_0/weights/*.bin  → weights_group0.h (Q8.8 and optional Q1.7)
  - group_0/*.bin         → test_images_group0.h (if present)

Usage:
  python bin2headers_group0.py [--group-dir PATH] [--output-dir PATH]
"""

import argparse
import struct
from pathlib import Path


def bin_to_define(binfile: Path, name: str, outfile, comment: str = None) -> None:
    """Read binary int16 (Q8.8) and emit #define macro."""
    with open(binfile, "rb") as f:
        data = f.read()
    values = struct.unpack("<" + "h" * (len(data) // 2), data)
    if comment:
        outfile.write(f"// {comment}\n")
    outfile.write(f"#define {name} ")
    outfile.write(",".join(str(v) for v in values))
    outfile.write("\n\n")


def bin_to_define_q17(binfile: Path, name: str, outfile, comment: str = None) -> None:
    """Convert Q8.8 to Q1.7 (Tip 2) and emit #define macro."""
    with open(binfile, "rb") as f:
        data = f.read()
    values_q88 = struct.unpack("<" + "h" * (len(data) // 2), data)
    values_q17 = [max(-128, min(127, v >> 1)) for v in values_q88]
    if comment:
        outfile.write(f"// {comment} (Q1.7 Tip 2)\n")
    outfile.write(f"#define {name}_q17 ")
    outfile.write(",".join(str(v) for v in values_q17))
    outfile.write("\n\n")


def generate_weights_h(group_dir: Path, out_dir: Path, with_q17: bool = True) -> None:
    """Generate weights_group0.h from group_0/weights/*.bin"""
    weights_dir = group_dir / "weights"
    if not weights_dir.exists():
        print(f"Warning: {weights_dir} not found, skipping weights")
        return

    out_path = out_dir / "weights_group0.h"
    with open(out_path, "w", encoding="utf-8") as out:
        out.write("/*\n * weights_group0.h\n")
        out.write(" * Auto-generated by bin2headers_group0.py\n")
        out.write(" * Group 0 DNN: 784->64->10 (2 FC layers)\n */\n\n")
        out.write("#ifndef WEIGHTS_GROUP0_H_\n#define WEIGHTS_GROUP0_H_\n\n")

        # FC0: 784→64
        for suffix, macro, desc in [
            ("Gemm0_biases.bin", "bias0", "FC0 bias: 64"),
            ("Gemm0_weights.bin", "weights0", "FC0 weights: 64x784"),
        ]:
            p = weights_dir / suffix
            if p.exists():
                bin_to_define(p, macro, out, desc)
                if with_q17:
                    bin_to_define_q17(p, macro, out, desc)
            else:
                print(f"Warning: {p} not found")

        # FC1: 64→10
        for suffix, macro, desc in [
            ("Gemm1_biases.bin", "bias1", "FC1 bias: 10"),
            ("Gemm1_weights.bin", "weights1", "FC1 weights: 10x64"),
        ]:
            p = weights_dir / suffix
            if p.exists():
                bin_to_define(p, macro, out, desc)
                if with_q17:
                    bin_to_define_q17(p, macro, out, desc)
            else:
                print(f"Warning: {p} not found")

        out.write("#endif /* WEIGHTS_GROUP0_H_ */\n")

    print(f"Written: {out_path}")


def generate_test_images_h(group_dir: Path, out_dir: Path) -> None:
    """Generate test_images_group0.h from group_0/*.bin (0.bin .. 9.bin)"""
    out_path = out_dir / "test_images_group0.h"
    macros = []
    for digit in range(10):
        p = group_dir / f"{digit}.bin"
        if not p.exists():
            print(f"Warning: {p} not found, skipping test_images")
            return
        with open(p, "rb") as f:
            data = f.read()
        if len(data) != 784 * 2:
            print(f"Warning: {p} has {len(data)} bytes (expected 1568), skipping")
            return
        values = struct.unpack("<" + "h" * 784, data)
        macros.append((f"imm_test_{digit}", ",".join(str(v) for v in values)))

    with open(out_path, "w", encoding="utf-8") as out:
        out.write("/*\n * test_images_group0.h\n")
        out.write(" * Auto-generated by bin2headers_group0.py\n")
        out.write(" * MNIST test images (digits 0-9) in Q8.8\n */\n\n")
        out.write("#ifndef TEST_IMAGES_GROUP0_H_\n#define TEST_IMAGES_GROUP0_H_\n\n")
        for name, vals in macros:
            out.write(f"#define {name} {vals}\n\n")
        out.write("#endif /* TEST_IMAGES_GROUP0_H_ */\n")

    print(f"Written: {out_path}")


def main():
    parser = argparse.ArgumentParser(
        description="Convert Group 0 binary files to C headers"
    )
    parser.add_argument(
        "--group-dir",
        type=Path,
        default=Path(__file__).parent / "aes_mnist_assigment_groups" / "group_0",
        help="Path to group_0 folder",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path(__file__).parent / "aes_mnist_assigment_groups" / "group_0",
        help="Output directory for .h files",
    )
    parser.add_argument(
        "--no-q17",
        action="store_true",
        help="Skip Q1.7 (Tip 2) macros in weights",
    )
    parser.add_argument(
        "--weights-only",
        action="store_true",
        help="Generate only weights_group0.h",
    )
    args = parser.parse_args()

    args.output_dir.mkdir(parents=True, exist_ok=True)

    generate_weights_h(args.group_dir, args.output_dir, with_q17=not args.no_q17)

    if not args.weights_only:
        generate_test_images_h(args.group_dir, args.output_dir)


if __name__ == "__main__":
    main()
